name = "my name is liugang"
name2 = "my name is {name} and i'm age is {old}"

print(name.capitalize())
print(name.count("m"))
print(name.center(5,"-"))
print(name.endswith("@dic.com.cn"))
print(name.expandtabs(tabsize=10))
print(name.find("name"))
print(name[name.find("name"):])
print(name2.format(name='liugang',old=33))
print(name2.format_map({'name':'liugang','old':33}))
print(name.index("name"))
print('abc'.isalnum())
print('xxx787'.isalpha())
print('10B'.isdecimal())
print('111'.isdigit())
print('_A_1_'.isidentifier())
print('xx'.islower())
print('AA'.isupper())
print('22.2'.isnumeric())
print(' '.isspace())
print('MyNameIs '.istitle())
print('xxx'.isprintable())
print('My name is'.join("=="))