name = "my name is liugang"
name2 = "my name is {name} and i'm age is {old}"

print(name.capitalize())
print(name.count("m"))
print(name.center(5,"-"))
print(name.endswith("@dic.com.cn"))
print(name.expandtabs(tabsize=10))
print(name.find("name"))
print(name[name.find("name"):])
print(name2.format(name='liugang',old=33))
print(name2.format_map({'name':'liugang','old':33}))
print(name.index("name"))
print('abc'.isalnum())
print('xxx787'.isalpha())
print('10B'.isdecimal())
print('111'.isdigit())
print('_A_1_'.isidentifier())
print('xx'.islower())
print('AA'.isupper())
print('22.2'.isnumeric())
print(' '.isspace())
print('MyNameIs '.istitle())
print('xxx'.isprintable())
print(':'.join(['1','2','3','4']))
print(name.ljust(19,"*"))
print(name.rjust(50,"*"))
print('  liugang\n'.lstrip())
print('  liugang '.rstrip())
print('  liugagn  '.strip())
#print('liugang\n'.maketrans())
p = str.maketrans("ign","123")
print("liugang".translate(p))
print("liugang".replace("g","b"))
print("liugang".replace("g","b",1))
print("liugang".rfind("g"))
print("I|love|liugang".split("|"))
print("I love\n liugang".splitlines())
print("liu gang".swapcase())
print("liu gang".title())
print("liugang".zfill(50))